#!/bin/bash

# Automated USB Latency Timer Setup Script
# Detects FTDI USB-serial devices and creates udev rule automatically

set -e

echo "========================================="
echo "USB Latency Timer Setup for Dynamixel"
echo "========================================="
echo ""

# Check if running with sudo
if [ "$EUID" -ne 0 ]; then
    echo "This script needs sudo privileges to install udev rules."
    echo "Restarting with sudo..."
    echo ""
    exec sudo bash "$0" "$@"
fi

# Detect FTDI devices (vendor ID 0403)
echo "Scanning for FTDI USB-serial devices..."
echo ""

# Get FTDI devices with details
ftdi_devices=$(lsusb | grep "0403:" || true)

if [ -z "$ftdi_devices" ]; then
    echo "ERROR: No FTDI devices found!"
    echo ""
    echo "Please check:"
    echo "  1. USB device is plugged in"
    echo "  2. Device is powered on"
    echo "  3. USB cable is working"
    echo ""
    echo "All USB devices:"
    lsusb
    exit 1
fi

echo "Found FTDI device(s):"
echo "$ftdi_devices"
echo ""

# Extract vendor and product IDs
# Format: Bus XXX Device XXX: ID VVVV:PPPP Description
vendor_id=$(echo "$ftdi_devices" | head -1 | sed 's/.*ID \([0-9a-f]\{4\}\):\([0-9a-f]\{4\}\).*/\1/')
product_id=$(echo "$ftdi_devices" | head -1 | sed 's/.*ID \([0-9a-f]\{4\}\):\([0-9a-f]\{4\}\).*/\2/')

# Count how many FTDI devices found
device_count=$(echo "$ftdi_devices" | wc -l)

if [ "$device_count" -gt 1 ]; then
    echo "WARNING: Multiple FTDI devices found!"
    echo "Using the first one: $vendor_id:$product_id"
    echo ""
    read -p "Continue? (y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled."
        exit 0
    fi
fi

echo "Device Information:"
echo "  Vendor ID:  $vendor_id"
echo "  Product ID: $product_id"
echo ""

# Create udev rule
rule_file="/etc/udev/rules.d/99-ftdi-latency.rules"

echo "Creating udev rule at: $rule_file"

cat > "$rule_file" << EOF
# Udev rule to set USB latency timer to 1ms for FTDI adapter
# This improves high-frequency motor control performance (80-120Hz)
#
# Auto-generated by setup_usb_latency.sh on $(date)
# Device: $ftdi_devices
# Vendor ID: $vendor_id, Product ID: $product_id
#
# To verify (after replugging device):
#   cat /sys/bus/usb-serial/devices/ttyUSB*/latency_timer
#   (should show: 1)

ACTION=="add", SUBSYSTEM=="usb-serial", ATTRS{idVendor}=="$vendor_id", ATTRS{idProduct}=="$product_id", ATTR{latency_timer}="1"
EOF

echo "Udev rule created successfully!"
echo ""

# Reload udev rules
echo "Reloading udev rules..."
udevadm control --reload-rules

echo "Triggering udev rules..."
udevadm trigger

echo ""
echo "========================================="
echo "Setup Complete!"
echo "========================================="
echo ""
echo "The USB latency timer will now be automatically set to 1ms"
echo "whenever you plug in this device."
echo ""
echo "To verify:"
echo "  1. Unplug and replug your USB device"
echo "  2. Run: cat /sys/bus/usb-serial/devices/ttyUSB*/latency_timer"
echo "  3. You should see: 1"
echo ""
echo "This setting persists across reboots!"
echo ""

# Try to verify if device is currently connected
if ls /sys/bus/usb-serial/devices/ttyUSB* &> /dev/null; then
    echo "Current latency timer value(s):"
    for device in /sys/bus/usb-serial/devices/ttyUSB*; do
        timer_value=$(cat "$device/latency_timer" 2>/dev/null || echo "N/A")
        echo "  $(basename $device): $timer_value"
    done
    echo ""
    if [ "$timer_value" = "1" ]; then
        echo "✓ Latency timer already set correctly!"
    else
        echo "Note: Unplug and replug the device for the change to take effect."
    fi
else
    echo "Note: USB device not currently detected. Plug it in to apply the setting."
fi

echo ""
